env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

name: Application Build & Test
on: [push, pull_request]
jobs:
  unit-test:
    name: UNIT TESTS
    runs-on: ubuntu-latest
    services:
      db:
        image: nouchka/sqlite3

    steps:
      - name: ⇒ Check-out repository
        uses: actions/checkout@v2

      - name: ⇒ Setup Ruby 3.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - name: ⇒ Setup database
        run: |
          bundle exec rails db:prepare

      - name: ⇒ Run unit-tests
        run: |
          bundle exec rspec

  integration-test:
    name: INTEGRATION TESTS
    runs-on: ubuntu-latest
    services:
      db:
        image: nouchka/sqlite3

    steps:
      - name: ⇒ Check-out repository
        uses: actions/checkout@v2

      - name: ⇒ Setup Ruby 3.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - name: ⇒ Setup database
        run: |
          bundle exec rails db:prepare

      - uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1920x1080 > /dev/null 2>&1 & # optional

      - name: ⇒ Run integration-tests
        run: |
          bundle exec rspec spec/features/*
